export enum InvoiceCatRegimenFiscal {
  'General de Ley Personas Morales' = '601',
  'Personas Morales con Fines no Lucrativos' = '603',
  'Sueldos y Salarios e Ingresos Asimilados a Salarios' = '605',
  'Arrendamiento' = '606',
  'Régimen de Enajenación o Adquisición de Bienes' = '607',
  'Demás ingresos' = '608',
  'Consolidación' = '609',
  'Residentes en el Extranjero sin Establecimiento Permanente en México' = '610',
  'Ingresos por Dividendos (socios y accionistas)' = '611',
  'Personas Físicas con Actividades Empresariales y Profesionales' = '612',
  'Ingresos por intereses' = '614',
  'Régimen de los ingresos por obtención de premios' = '615',
  'Sin obligaciones fiscales' = '616',
  'Sociedades Cooperativas de Producción que optan por diferir sus ingresos' = '620',
  'Incorporación Fiscal' = '621',
  'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras' = '622',
  'Opcional para Grupos de Sociedades' = '623',
  'Coordinados' = '624',
  'Hidrocarburos' = '628',
  'De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales' = '629',
  'Enajenación de acciones en bolsa de valores' = '630',
}
